### ISSUE TITLE
Error : Ed25519: bad private key length: 96

### ISSUE THREAD

**Issue by amintalebi** [islishude/bip32#7]
PrivateKey size exceeds ed25519 private key size. as a result It panics when you try to sign a message.
`k` type is `XPrv`.

```
p := ed25519.PrivateKey(k)
signData, err := p.Sign(rand.Reader, payload, crypto.Hash(0))
if err != nil {
  return err
}
```

**Comment by islishude** [comment]
the 96 bytes key is extend private key not private key

**Comment by islishude** [comment]
use xrpv.Sign() to sign a message. see document here https://pkg.go.dev/github.com/islishude/bip32#XPrv.Sign

**Comment by amintalebi** [comment]
Thanks, it worked. I was looking for something to work with signature scheme of Solana and your package helped a lot.
